#language: objective-c
#xcode_project: gtestDemo.xcodeproj # path to your xcodeproj folder
#xcode_scheme: gtestDemo
#xcode_sdk: iphonesimulator
osx_image: xcode7.3
script:xctool -project gtestDemo.xcodeproj -scheme gtestDemo -sdk iphonesimulator
